#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rmfakecloud"
name = "rmfakecloud"
description.en = "Self-hosted cloud service and web UI for reMarkable devices"
description.fr = "Service cloud auto-hébergé et interface web pour appareils reMarkable"

version = "0.0.31~ynh2"

maintainers = ["wazdra"]

[upstream]
license = "AGPL-3.0-only"
website = "https://ddvk.github.io/rmfakecloud/"
admindoc = "https://doc.yunohost.org/dev/packaging/"
userdoc = "https://ddvk.github.io/rmfakecloud/remarkable/setup/"
code = "https://github.com/ddvk/rmfakecloud"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false


disk = "2G"
ram.build = "1500M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    # The app must be installed at the root of a (sub)domain.

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Password for the initial rmfakecloud administrator account. This is a separate account from your YunoHost one -- rmfakecloud has no LDAP support, so it cannot reuse YunoHost logins."
    help.fr = "Mot de passe du compte administrateur initial de rmfakecloud. Ce compte est distinct de votre compte YunoHost : rmfakecloud ne gère pas LDAP et ne peut donc pas réutiliser les identifiants YunoHost."
    type = "password"

[antifeatures]

alpha-software.en = "Upstream is still work in progress."

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/ddvk/rmfakecloud/archive/refs/tags/v0.0.31.tar.gz"
    sha256 = "702544eb5bf5b2f750428917e0b0b1610afb694233a25fb278a162820e1b91de"


    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]


    [resources.data_dir]


    [resources.permissions]
    main.url = "/"
    main.allowed = "visitors"

    [resources.ports]
    main.default = 3000
    mqtt.default = 8883

    [resources.go]
    version = "1.24.1"

    [resources.nodejs]
    version = "22"
