#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rmfakecloud"
name = "rmfakecloud"
description.en = "Self-hosted cloud service and web UI for reMarkable devices"
description.fr = "Service cloud auto-hébergé et interface web pour appareils reMarkable"

version = "0.0.31~ynh1"

maintainers = ["anatoledahan"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "AGPL-3.0-only"
website = "https://ddvk.github.io/rmfakecloud/"
admindoc = "https://doc.yunohost.org/dev/packaging/"
userdoc = "https://ddvk.github.io/rmfakecloud/remarkable/setup/"
code = "https://github.com/ddvk/rmfakecloud"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "500M"
ram.build = "500M"
ram.runtime = "150M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/"

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

    [resources.sources.main]
    # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
    #    ynh_setup_source --dest_dir="$install_dir"
    # You can also define other assets than "main" and add --source_id="foobar" in the previous command
    url = "https://github.com/ddvk/rmfakecloud/archive/refs/tags/v0.0.31.tar.gz"
    sha256 = "702544eb5bf5b2f750428917e0b0b1610afb694233a25fb278a162820e1b91de"

    # These infos are used by https://github.com/YunoHost/apps_tools/blob/main/autoupdate_app_sources/autoupdate_app_sources.py
    # to auto-update the previous asset urls and sha256sum + manifest version
    # assuming the upstream's code repo is on github and relies on tags or releases
    # See the 'sources' resource documentation for more details

    autoupdate.strategy = "latest_github_tag"

    [resources.go]
    version = "1.24.1"

    [resources.nodejs]
    version = "22"
    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir


    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    main.default = 3000

