#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# DECLARE SETTINGS
#=================================================

jwt_secret_key="$(openssl rand -base64 48)"
storage_url="https://$domain$path"
loglevel="info"

ynh_app_setting_set --key=jwt_secret_key --value="$jwt_secret_key"
ynh_app_setting_set --key=storage_url --value="$storage_url"
ynh_app_setting_set --key=loglevel --value="$loglevel"

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=version --value="0.0.31"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

### `ynh_setup_source` is used to install an app from a zip or tar.gz file,
### downloaded from an upstream source, like a git repository.
### `ynh_setup_source` use the file manifest.toml

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

### $install_dir will automatically be initialized with some decent
### permission by default... however, you may need to recursively reapply
### ownership to all files such as after the ynh_setup_source step
chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:$app" "$install_dir"

#=================================================
# BUILD APPLICATION
#=================================================
ynh_script_progression "Building rmfakecloud..."

pushd "$install_dir/ui" >/dev/null
corepack prepare pnpm@latest-9 --activate
pnpm install --frozen-lockfile
pnpm build
popd >/dev/null

go build -o "$install_dir/rmfakecloud" ./cmd/rmfakecloud
chown "$app:$app" "$install_dir/rmfakecloud"
### which will automatically be replaced by the values of $foo and $foo_bar
###
### ynh_config_add will also keep track of the config file's checksum,
### which later during upgrade may allow to automatically backup the config file
### if it's found that the file was manually modified

rmfakecloud_write_environment "$jwt_secret_key" "$storage_url" "$loglevel"
###   - You can remove these files in conf/.
###   - Remove the section "BACKUP THE PHP-FPM CONFIGURATION" in the backup script
###   - Remove also the section "REMOVE PHP-FPM CONFIGURATION" in the remove script
###   - As well as the section "RESTORE THE PHP-FPM CONFIGURATION" in the restore script
###     with the reload at the end of the script.
###   - Remove the section "BACKUP SYSTEMD" in the backup script
###   - Remove also the section "STOP AND REMOVE SERVICE" in the remove script
###   - As well as the section "RESTORE SYSTEMD" in the restore script
###   - As well as the section "INTEGRATE SERVICE IN YUNOHOST" in the restore script
###   - And the section "INTEGRATE SERVICE IN YUNOHOST" in the upgrade script


yunohost service add "$app" --description="rmfakecloud"
### forms.

###   - As well as the section "START SYSTEMD SERVICE" in the restore script
###   - As well as the section"STOP SYSTEMD SERVICE" and "START SYSTEMD SERVICE" in the upgrade script
###   - And the section "STOP SYSTEMD SERVICE" and "START SYSTEMD SERVICE" in the change_url script

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
